# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetDelta <- function(time, delta4Fac, deltaM, tc, deadStageIdx) {
    .Call(`_hivModelling_GetDelta`, time, delta4Fac, deltaM, tc, deadStageIdx)
}

GetBSplineCubic <- function(time, theta, myKnots, k) {
    .Call(`_hivModelling_GetBSplineCubic`, time, theta, myKnots, k)
}

GetBSpline <- function(time, theta, kOrder, modelSplineN, myKnots, minYear, maxYear) {
    .Call(`_hivModelling_GetBSpline`, time, theta, kOrder, modelSplineN, myKnots, minYear, maxYear)
}

Swap1D <- function(y, a, b) {
    invisible(.Call(`_hivModelling_Swap1D`, y, a, b))
}

Swap2D <- function(y, a1, a2, b1, b2) {
    invisible(.Call(`_hivModelling_Swap2D`, y, a1, a2, b1, b2))
}

OdeintCountLoop <- function(modelYears, param, info) {
    .Call(`_hivModelling_OdeintCountLoop`, modelYears, param, info)
}

OdeintCountReturn <- function(ystart, nVar, x1, x2, param, info, minYear, maxYear) {
    .Call(`_hivModelling_OdeintCountReturn`, ystart, nVar, x1, x2, param, info, minYear, maxYear)
}

OdeintTimeReturn <- function(ystart, nVar, x1, x2, param, info, minYear, maxYear, tmpYear) {
    .Call(`_hivModelling_OdeintTimeReturn`, ystart, nVar, x1, x2, param, info, minYear, maxYear, tmpYear)
}

FitLLNegBin <- function(y_m, y_d, r) {
    .Call(`_hivModelling_FitLLNegBin`, y_m, y_d, r)
}

FitLLPoisson <- function(y_m, y_d) {
    .Call(`_hivModelling_FitLLPoisson`, y_m, y_d)
}

Zbrent <- function(func, x1, x2, tol, extraArgs) {
    .Call(`_hivModelling_Zbrent`, func, x1, x2, tol, extraArgs)
}

