# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetDelta <- function(time, delta4Fac, deltaM, tc, deadStageIdx) {
    .Call(`_hivModelling_GetDelta`, time, delta4Fac, deltaM, tc, deadStageIdx)
}

GetBSplineCubic <- function(time, theta, myKnots, k) {
    .Call(`_hivModelling_GetBSplineCubic`, time, theta, myKnots, k)
}

GetBSpline <- function(time, theta, kOrder, modelSplineN, myKnots, minYear, maxYear) {
    .Call(`_hivModelling_GetBSpline`, time, theta, kOrder, modelSplineN, myKnots, minYear, maxYear)
}

Swap1D <- function(y, a, b) {
    invisible(.Call(`_hivModelling_Swap1D`, y, a, b))
}

Swap2D <- function(y, a1, a2, b1, b2) {
    invisible(.Call(`_hivModelling_Swap2D`, y, a1, a2, b1, b2))
}

DetermineIloIhi <- function(y, ilo, ihi, inhi) {
    invisible(.Call(`_hivModelling_DetermineIloIhi`, y, ilo, ihi, inhi))
}

CountOdeintLoop <- function() {
    .Call(`_hivModelling_CountOdeintLoop`)
}

CountOdeintReturn <- function(ystart, nVar, x1, x2, minYear, maxYear) {
    .Call(`_hivModelling_CountOdeintReturn`, ystart, nVar, x1, x2, minYear, maxYear)
}

SetCountModelParameters <- function(param, info) {
    invisible(.Call(`_hivModelling_SetCountModelParameters`, param, info))
}

TimeOdeintReturn <- function(ystart, x1, x2, minYear, maxYear, tmpYear) {
    .Call(`_hivModelling_TimeOdeintReturn`, ystart, x1, x2, minYear, maxYear, tmpYear)
}

ModelTimeToDiagMedian <- function(time) {
    .Call(`_hivModelling_ModelTimeToDiagMedian`, time)
}

FitLLNegBin <- function(y_m, y_d, r) {
    .Call(`_hivModelling_FitLLNegBin`, y_m, y_d, r)
}

FitLLPoisson <- function(y_m, y_d) {
    .Call(`_hivModelling_FitLLPoisson`, y_m, y_d)
}

Zbrent <- function(func, x1, x2, tol, extraArgs) {
    .Call(`_hivModelling_Zbrent`, func, x1, x2, tol, extraArgs)
}

Seq <- function(start, end) {
    .Call(`_hivModelling_Seq`, start, end)
}

