# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetBSpline_c <- function(time, param, info) {
    .Call(`_hivModelling_GetBSpline_c`, time, param, info)
}

GetDelta_c <- function(time, param) {
    .Call(`_hivModelling_GetDelta_c`, time, param)
}

derivsFunc_c <- function(x, y, lambda, nVar, param) {
    .Call(`_hivModelling_derivsFunc_c`, x, y, lambda, nVar, param)
}

